# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pytypes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pytypes.proto',
  package='carp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpytypes.proto\x12\x04\x63\x61rp\"\xe5\x01\n\x0bPythonValue\x12\x11\n\x07_string\x18\x01 \x01(\tH\x00\x12\x11\n\x07_double\x18\x02 \x01(\x01H\x00\x12\x0e\n\x04_int\x18\x03 \x01(\x12H\x00\x12\x10\n\x06_bytes\x18\x04 \x01(\x0cH\x00\x12\x15\n\x0b_serialized\x18\x05 \x01(\x0cH\x00\x12\x0f\n\x05_bool\x18\x06 \x01(\x08H\x00\x12\x0f\n\x05_none\x18\x07 \x01(\x08H\x00\x12#\n\x06_array\x18\x08 \x01(\x0b\x32\x11.carp.PythonArrayH\x00\x12!\n\x05_dict\x18\t \x01(\x0b\x32\x10.carp.PythonDictH\x00\x42\r\n\x0bvalue_types\"R\n\x0ePythonDictItem\x12\x1e\n\x03key\x18\x01 \x01(\x0b\x32\x11.carp.PythonValue\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.carp.PythonValue\"1\n\nPythonDict\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.carp.PythonDictItem\"/\n\x0bPythonArray\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.carp.PythonValue\"8\n\x14PythonValueContainer\x12 \n\x05value\x18\x01 \x01(\x0b\x32\x11.carp.PythonValue\"8\n\x14PythonArrayContainer\x12 \n\x05value\x18\x01 \x01(\x0b\x32\x11.carp.PythonArray\"6\n\x13PythonDictContainer\x12\x1f\n\x05value\x18\x01 \x01(\x0b\x32\x10.carp.PythonDictb\x06proto3'
)




_PYTHONVALUE = _descriptor.Descriptor(
  name='PythonValue',
  full_name='carp.PythonValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_string', full_name='carp.PythonValue._string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_double', full_name='carp.PythonValue._double', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_int', full_name='carp.PythonValue._int', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_bytes', full_name='carp.PythonValue._bytes', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_serialized', full_name='carp.PythonValue._serialized', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_bool', full_name='carp.PythonValue._bool', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_none', full_name='carp.PythonValue._none', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_array', full_name='carp.PythonValue._array', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='_dict', full_name='carp.PythonValue._dict', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value_types', full_name='carp.PythonValue.value_types',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=24,
  serialized_end=253,
)


_PYTHONDICTITEM = _descriptor.Descriptor(
  name='PythonDictItem',
  full_name='carp.PythonDictItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='carp.PythonDictItem.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='carp.PythonDictItem.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=337,
)


_PYTHONDICT = _descriptor.Descriptor(
  name='PythonDict',
  full_name='carp.PythonDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='carp.PythonDict.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=388,
)


_PYTHONARRAY = _descriptor.Descriptor(
  name='PythonArray',
  full_name='carp.PythonArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='carp.PythonArray.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=437,
)


_PYTHONVALUECONTAINER = _descriptor.Descriptor(
  name='PythonValueContainer',
  full_name='carp.PythonValueContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='carp.PythonValueContainer.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=495,
)


_PYTHONARRAYCONTAINER = _descriptor.Descriptor(
  name='PythonArrayContainer',
  full_name='carp.PythonArrayContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='carp.PythonArrayContainer.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=553,
)


_PYTHONDICTCONTAINER = _descriptor.Descriptor(
  name='PythonDictContainer',
  full_name='carp.PythonDictContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='carp.PythonDictContainer.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=609,
)

_PYTHONVALUE.fields_by_name['_array'].message_type = _PYTHONARRAY
_PYTHONVALUE.fields_by_name['_dict'].message_type = _PYTHONDICT
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_string'])
_PYTHONVALUE.fields_by_name['_string'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_double'])
_PYTHONVALUE.fields_by_name['_double'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_int'])
_PYTHONVALUE.fields_by_name['_int'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_bytes'])
_PYTHONVALUE.fields_by_name['_bytes'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_serialized'])
_PYTHONVALUE.fields_by_name['_serialized'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_bool'])
_PYTHONVALUE.fields_by_name['_bool'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_none'])
_PYTHONVALUE.fields_by_name['_none'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_array'])
_PYTHONVALUE.fields_by_name['_array'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONVALUE.oneofs_by_name['value_types'].fields.append(
  _PYTHONVALUE.fields_by_name['_dict'])
_PYTHONVALUE.fields_by_name['_dict'].containing_oneof = _PYTHONVALUE.oneofs_by_name['value_types']
_PYTHONDICTITEM.fields_by_name['key'].message_type = _PYTHONVALUE
_PYTHONDICTITEM.fields_by_name['value'].message_type = _PYTHONVALUE
_PYTHONDICT.fields_by_name['items'].message_type = _PYTHONDICTITEM
_PYTHONARRAY.fields_by_name['items'].message_type = _PYTHONVALUE
_PYTHONVALUECONTAINER.fields_by_name['value'].message_type = _PYTHONVALUE
_PYTHONARRAYCONTAINER.fields_by_name['value'].message_type = _PYTHONARRAY
_PYTHONDICTCONTAINER.fields_by_name['value'].message_type = _PYTHONDICT
DESCRIPTOR.message_types_by_name['PythonValue'] = _PYTHONVALUE
DESCRIPTOR.message_types_by_name['PythonDictItem'] = _PYTHONDICTITEM
DESCRIPTOR.message_types_by_name['PythonDict'] = _PYTHONDICT
DESCRIPTOR.message_types_by_name['PythonArray'] = _PYTHONARRAY
DESCRIPTOR.message_types_by_name['PythonValueContainer'] = _PYTHONVALUECONTAINER
DESCRIPTOR.message_types_by_name['PythonArrayContainer'] = _PYTHONARRAYCONTAINER
DESCRIPTOR.message_types_by_name['PythonDictContainer'] = _PYTHONDICTCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PythonValue = _reflection.GeneratedProtocolMessageType('PythonValue', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONVALUE,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonValue)
  })
_sym_db.RegisterMessage(PythonValue)

PythonDictItem = _reflection.GeneratedProtocolMessageType('PythonDictItem', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONDICTITEM,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonDictItem)
  })
_sym_db.RegisterMessage(PythonDictItem)

PythonDict = _reflection.GeneratedProtocolMessageType('PythonDict', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONDICT,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonDict)
  })
_sym_db.RegisterMessage(PythonDict)

PythonArray = _reflection.GeneratedProtocolMessageType('PythonArray', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONARRAY,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonArray)
  })
_sym_db.RegisterMessage(PythonArray)

PythonValueContainer = _reflection.GeneratedProtocolMessageType('PythonValueContainer', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONVALUECONTAINER,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonValueContainer)
  })
_sym_db.RegisterMessage(PythonValueContainer)

PythonArrayContainer = _reflection.GeneratedProtocolMessageType('PythonArrayContainer', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONARRAYCONTAINER,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonArrayContainer)
  })
_sym_db.RegisterMessage(PythonArrayContainer)

PythonDictContainer = _reflection.GeneratedProtocolMessageType('PythonDictContainer', (_message.Message,), {
  'DESCRIPTOR' : _PYTHONDICTCONTAINER,
  '__module__' : 'pytypes_pb2'
  # @@protoc_insertion_point(class_scope:carp.PythonDictContainer)
  })
_sym_db.RegisterMessage(PythonDictContainer)


# @@protoc_insertion_point(module_scope)
